language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm run test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
